/*
*** Primary Color:

   var. 1 = #A72CA2 = rgb(167,44,162)
   var. 2 = #763973 = rgb(118,57,115)
   var. 3 = #620B5E = rgb(98,11,94)
   var. 4 = #D663D1 = rgb(214,99,209)
   var. 5 = #D685D3 = rgb(214,133,211)

*** Complementary Color:

   var. 1 = #D1F240 = rgb(209,242,64)
   var. 2 = #9AAA52 = rgb(154,170,82)
   var. 3 = #768D0F = rgb(118,141,15)
   var. 4 = #E1F973 = rgb(225,249,115)
   var. 5 = #E8F99B = rgb(232,249,155)
*/
/*
#####  Color Palette by Color Scheme Designer
#####  Palette URL: http://colorschemedesigner.com/#4z21TnvvvAXyw


*** Primary Color:

   var. 1 = #7136A9 = rgb(113,54,169)
   var. 2 = #5B3E77 = rgb(91,62,119)
   var. 3 = #390D63 = rgb(57,13,99)
   var. 4 = #A36CD8 = rgb(163,108,216)
   var. 5 = #B28CD8 = rgb(178,140,216)

*** Complementary Color:

   var. 1 = #FBF143 = rgb(251,241,67)
   var. 2 = #B1AB55 = rgb(177,171,85)
   var. 3 = #938B10 = rgb(147,139,16)
   var. 4 = #FDF675 = rgb(253,246,117)
   var. 5 = #FDF89D = rgb(253,248,157)


#####  Generated by Color Scheme Designer © Petr Stanicek 2002-2009

#####  Color Palette by Color Scheme Designer
#####  Palette URL: http://colorschemedesigner.com/#3E32CjX--uDIu


*** Primary Color:

   var. 1 = #6EABFF = rgb(110,171,255)
   var. 2 = #6E91C2 = rgb(110,145,194)
   var. 3 = #265DAA = rgb(38,93,170)
   var. 4 = #A1C9FF = rgb(161,201,255)
   var. 5 = #CBE1FF = rgb(203,225,255)

*** Secondary Color A:

   var. 1 = #ECFF60 = rgb(236,255,96)
   var. 2 = #B7C266 = rgb(183,194,102)
   var. 3 = #99AA21 = rgb(153,170,33)
   var. 4 = #F3FF99 = rgb(243,255,153)
   var. 5 = #F8FFC6 = rgb(248,255,198)

*** Secondary Color B:

   var. 1 = #FF60A8 = rgb(255,96,168)
   var. 2 = #C26690 = rgb(194,102,144)
   var. 3 = #AA215F = rgb(170,33,95)
   var. 4 = #FF99C7 = rgb(255,153,199)
   var. 5 = #FFC6E0 = rgb(255,198,224)


#####  Generated by Color Scheme Designer © Petr Stanicek 2002-2009

*/